development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: agenda_development
  pool: 5
  username: agenda
  password: agenda123

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: agenda_test
  pool: 5
  username: agenda
  password: agenda123

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: agenda_production
  pool: 5
  username: agenda
  password: agenda123
